Create README-fr.md file
nostalgic-css/NES.css pull request #439
Opened 2020-10-01 00:44 UTC by xroll

# Add french translation README

**Description**
Add french translation README markdown

**Compatibility**
add one file README-fr.md in .github/

**Caveats**

2020-10-01 01:18 UTC, guastallaigor requested changes
Thank you for your contribution 🎉 

Two things:
1. This PR has a commitlint error. 

Could you change your commit message to something like `fix: update icon-mixin.scss` 🙇 

The git commands shoud be something like this:
```shell
# edit your commit message
$ git commit --amend -m "fix: update icon-mixin.scss"

# force push branch
$ git push --force-with-lease origin patch-1
```

The second one I will add a comment below.

2020-10-01 01:18 UTC, guastallaigor commented on .github/README-fr.md
> +  <a href=".github/README-jp.md">日本語</a> / <a href=".github/README-zh-CN.md">简体中文</a> / <a href=".github/README-es.md">Español</a> / <a href=".github/README-pt-BR.md">Português</a> / <a href=".github
Could you add the `<a href=".github/README-fr.md" Français</a>` in the other `README.md` files as well?

2020-10-01 12:00 UTC, xroll commented
Understood, i will make changes and lint commit. Kind regards.

2020-10-02 15:17 UTC, guastallaigor commented
ref #440

2020-10-02 15:17 UTC, closed without merging